# Generated by Django 3.2.6 on 2023-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_username', models.CharField(max_length=100)),
                ('school_items', models.IntegerField()),
                ('health', models.IntegerField()),
                ('transportation', models.IntegerField()),
                ('clothes', models.IntegerField()),
                ('bills', models.IntegerField()),
                ('sports', models.IntegerField()),
                ('extra_curricular', models.IntegerField()),
                ('notes', models.CharField(default='', max_length=300)),
                ('current_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_username', models.CharField(max_length=100)),
                ('school_items', models.IntegerField()),
                ('health', models.IntegerField()),
                ('transportation', models.IntegerField()),
                ('clothes', models.IntegerField()),
                ('bills', models.IntegerField()),
                ('sports', models.IntegerField()),
                ('extra_curricular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
                ('classrooms', models.IntegerField()),
                ('laboratories', models.IntegerField()),
                ('library', models.IntegerField()),
                ('computer_labs', models.IntegerField()),
                ('staff_rooms', models.IntegerField()),
                ('students', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('administrative_staffs', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=100)),
            ],
        ),
    ]
