# Generated by Django 3.2.6 on 2023-03-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='pan',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
