# Generated by Django 3.2.6 on 2023-03-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolform_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='image_file',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
