# Generated by Django 3.2.6 on 2023-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schoolform_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
