# Generated by Django 3.2.6 on 2023-03-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_schoolform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='educational_background',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolform',
            name='vision_for_school',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolform',
            name='years_of_experience',
            field=models.IntegerField(default=5),
        ),
    ]
