# Generated by Django 3.2.6 on 2023-03-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20230331_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolform',
            name='years_of_experience',
            field=models.IntegerField(),
        ),
    ]
