# Generated by Django 3.2.6 on 2023-04-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_schoolform_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrack',
            name='food',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
