# Generated by Django 3.2.6 on 2023-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_dailytrack_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbudget',
            name='distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolbudget',
            name='bills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolbudget',
            name='clothes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolbudget',
            name='extra_curricular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolbudget',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolbudget',
            name='school_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolbudget',
            name='sports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolbudget',
            name='transportation',
            field=models.IntegerField(default=0),
        ),
    ]
