# Generated by Django 3.2.6 on 2023-04-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20230428_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbudget',
            name='food',
            field=models.IntegerField(default=0),
        ),
    ]
