# Generated by Django 3.2.6 on 2023-05-03 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_dailysavingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbudget',
            name='curr_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
