# Generated by Django 3.2.6 on 2023-05-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_schoolbudget_curr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_username', models.CharField(max_length=100)),
                ('school_items', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('transportation', models.IntegerField(default=0)),
                ('clothes', models.IntegerField(default=0)),
                ('bills', models.IntegerField(default=0)),
                ('sports', models.IntegerField(default=0)),
                ('extra_curricular', models.IntegerField(default=0)),
            ],
        ),
    ]
