# Generated by Django 3.2.6 on 2023-05-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_dailysavings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailySavings',
            new_name='DailySaving',
        ),
    ]
