# Generated by Django 3.2.6 on 2023-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_automate'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='account_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolform',
            name='bank_name',
            field=models.CharField(default='NIC Asia', max_length=100),
        ),
    ]
