# Generated by Django 3.2.6 on 2023-03-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
