# Generated by Django 3.2.6 on 2023-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='security_answer',
            field=models.CharField(default='not available', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='security_question',
            field=models.CharField(default='first word of the school if you want to rename your school', max_length=200),
        ),
    ]
